version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 50
  file-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 50
  method-count:
     config:
      threshold: 50
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 50
  return-statements:
    config:
      threshold: 50
  similar-code:
    config:
      threshold: 50
plugins:
  fixme:
    enabled: false
  csslint:
    enabled: false
  rubocop:
    enabled: false

exclude_patterns:
  - "spec/"
  - "!spec/support/helpers"
  - "nest1/"
