version: "2"         # required to adjust maintainability checks
checks:
  argument-count:
    config:
      threshold: 50
  complex-logic:
    config:
      threshold: 50
  file-lines:
    config:
      threshold: 50
  method-complexity:
    config:
      threshold: 50
  method-count:
    config:
      threshold: 50
  method-lines:
    config:
      threshold: 50
  nested-control-flow:
    config:
      threshold: 50
  return-statements:
    enabled: false
  similar-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
  identical-code:
    config:
      threshold: # language-specific defaults. an override will affect all languages.
plugins:
  fixme:
    enabled: true
  csslint:
    enabled: true
  rubocop:
    enabled: true

exclude_patterns:
  - "spec/"
  - "!spec/support/helpers"
  - "nest1/"
